# Generated by Django 4.2.10 on 2024-04-29 13:28

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_quantity_product_stock_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.qr__image_path),
        ),
    ]
