# Generated by Django 4.2.10 on 2024-04-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_purchase_due_alter_purchase_grand_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaselineup',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
