# Generated by Django 4.2.10 on 2024-04-30 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_product_quantity_sales_total_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlineup',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
