# Generated by Django 4.2.10 on 2024-05-02 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_customer_name_alter_customer_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
